export const TRADE_LICENSE_AUTHORITIES = [
    "Abu Dhabi Department of Economic Development (ADDED)",
    "Department of Economy and Tourism, Dubai",
    "Sharjah Department of Economic Development (SEDD)",
    "Ajman Department of Economic Development (AjmanDED)",
    "Umm Al Quwain Department of Economic Development (UAQDED)",
    "Ras Al Khaimah Department of Economic Development (RAKDED)",
    "Fujairah Department of Economic Development (FujairahDED)",
    "Abu Dhabi Global Market (ADGM)",
    "Khalifa Industrial Zone Abu Dhabi (KIZAD)",
    "Masdar City Free Zone",
    "Twofour54 (Media Zone Authority)",
    "Jebel Ali Free Zone Authority (JAFZA)",
    "Dubai Multi Commodities Centre (DMCC)",
    "Dubai Airport Free Zone Authority (DAFZA)",
    "Dubai Integrated Economic Zones Authority",
    "Dubai International Financial Centre (DIFC)",
    "Dubai South Free Zone",
    "Sharjah Airport International Free Zone (SAIF Zone)",
    "Hamriyah Free Zone Authority (HFZA)",
    "Ajman Free Zone Authority (AFZA)",
    "Ras Al Khaimah EconomicZone (RAKEZ)",
    "RAK Free Trade Zone (FTZ)",
    "Fujairah Free Zone Authority (FFZA)",
    "Umm Al Quwain Free Trade Zone (UAQFTZ)",
    "Meydan Free Zone",
];
